spring:
  application:
    name: main
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:${user.home}/.h2/maindb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"